server:
  port: 8084


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ConnectionServiceImpl?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: Gopal123*
  application:
    name: CONNECTION-SERVICE
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        '[format_sql]': true
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      fail-on-empty-beans: false



messageQ:
  Exchange: ConnExchange
  DL:
    Queue: DLQueue
    RoutingKey: DLConnection
  Infra:
    Queue: InfraQueue
    RoutingKey: InfraConnection

  Service:
    Queue: ServiceQueue
    RoutingKey: ServiceConnection

